```{r,include = FALSE}
library(tidyverse)
library(tidymodels)
library(mice) #package for imputation
library(VIM) #visualizing missingness
library(rpart) #for classification trees
library(rpart.plot) #for plotting trees
library(RColorBrewer) #better visualization of classification trees
library(rattle) #better visualization of classification trees
library(caret)
```

```{r}
heart = heart_disease
str(heart)
summary(heart)
```

```{r}
heart = heart %>% mutate(Sex = as_factor(Sex)) %>% 
  mutate(ChestPainType = as_factor(ChestPainType)) %>%
  mutate(RestingECG = as_factor(RestingECG)) %>%
  mutate(ExerciseAngina = as_factor(ExerciseAngina)) %>%
  mutate(ST_Slope = as_factor(ST_Slope)) %>%
  mutate(HeartDisease = as_factor(HeartDisease)) %>%
  mutate(HeartDisease = fct_recode(HeartDisease, "No" = "0", "Yes" = "1" )) 

str(heart)
```

```{r}
set.seed(12345) 
heart_split = initial_split(heart, prop = 0.7, strata = HeartDisease) 
train = training(heart_split)
test = testing(heart_split)
```

```{r}
heart_recipe = recipe(HeartDisease  ~., train)

heart_model = decision_tree() %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

heart_wflow = 
  workflow() %>% 
  add_model(heart_model) %>% 
  add_recipe(heart_recipe)

heart_fit = fit(heart_wflow, train)
```

```{r}
#extract the tree's fit from the fit object
tree = heart_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

#plot the tree
fancyRpartPlot(tree)
```

```{r}
fancyRpartPlot(tree, tweak=1.4
               ) #tweak makes the tree a little easier to read
```

```{r}
heart_fit$fit$fit$fit$cptable
```

```{r}
set.seed(123)
folds = vfold_cv(train, v = 5)
```

```{r}
heart_recipe_train = recipe(HeartDisease ~., train) %>%
  step_dummy(all_nominal(),-all_outcomes())

heart_model = decision_tree(cost_complexity = tune()) %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

heart_grid = grid_regular(cost_complexity(),
                          levels = 25) #try 25 sensible values for cp

heart_wflow = 
  workflow() %>% 
  add_model(heart_model) %>% 
  add_recipe(heart_recipe_train)

heart_res = 
  heart_wflow %>% 
  tune_grid(
    resamples = folds,
    grid = heart_grid
    )

heart_res
```

```{r}
heart_res %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity, mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) 
```

```{r}
best_heart = heart_res %>%
  select_best(metric = "accuracy")
best_heart
```

```{r}
heart_wf = 
  heart_wflow %>% 
  finalize_workflow(best_heart)
```

```{r}
final_fit = fit(heart_wf, train)

tree = final_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

fancyRpartPlot(tree, tweak = 1.2) 

```

```{r}
heartpred = predict(final_fit, train, type = "class")
head(heartpred)
```

```{r}
confusionMatrix(heartpred$.pred_class,train$HeartDisease,positive="Yes") 
```

```{r}
heartpred_test = predict(final_fit, test, type = "class")
head(heartpred_test)
```

```{r}
confusionMatrix(heartpred_test$.pred_class,test$HeartDisease,positive="Yes") #predictions first then actual
```


