```{r}
options(tidyverse.quiet = TRUE)
library(titanic)
library(tidyverse)
library(tidymodels)
library(mice) #package for imputation
library(VIM) #visualizing missingness
library(naniar) #visualizing missingness
library(skimr) #alternative way to view dataset summaries
library(UpSetR) #visualizing missingness
```

```{r}
grades = read_csv("class-grades.csv")
```

```{r}
str(grades)
summary(grades)
skim(grades)
```

```{r}
gg_miss_upset(grades, nsets = 6) #from the UpSetR package, must have at least two variables with missingness to use this plot
#note nsets = 7 refers to then number of variables to show in the plot. I chose 7 as there are 7 variables with missingness
```

```{r}
grades_rowdel = grades %>% drop_na() 
#alternatively can specify which variable(s) on which to do the drop_na
#drop_na(Age)
skim(grades_rowdel)
```


```{r}
grades_coldel = grades %>% drop_na() 
skim(grades_coldel)
```
```{r}
set.seed(123) #sets seed for random number generator
imp_grades = mice(grades, m=5, method='pmm', printFlag=FALSE)
#m is the number of imputations, 5 is a reasonable value as a default
#pmm is "predictive mean matching" = imputation method for numeric data
#printFlag reduces amount of output
summary(imp_grades)
```

```{r}
grades_complete = complete(imp_grades) 
summary(grades_complete)
```



















